"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ...file_utils import _BaseLazyModule, is_torch_available
from .configuration_fsmt import FSMTConfig, FSMT_PRETRAINED_CONFIG_ARCHIVE_MAP
from .tokenization_fsmt import FSMTTokenizer
from .modeling_fsmt import FSMTForConditionalGeneration, FSMTModel, PretrainedFSMTModel

_import_structure = { "configuration_fsmt": ["FSMT_PRETRAINED_CONFIG_ARCHIVE_MAP", "FSMTConfig"],"tokenization_fsmt": ["FSMTTokenizer"] }
if is_torch_available():
    ...
if is_torch_available():
    ...
