"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ...file_utils import _BaseLazyModule, is_sentencepiece_available, is_tf_available, is_tokenizers_available, is_torch_available
from .configuration_t5 import T5Config, T5_PRETRAINED_CONFIG_ARCHIVE_MAP
from .tokenization_t5 import T5Tokenizer
from .tokenization_t5_fast import T5TokenizerFast
from .modeling_t5 import T5EncoderModel, T5ForConditionalGeneration, T5Model, T5PreTrainedModel, T5_PRETRAINED_MODEL_ARCHIVE_LIST, load_tf_weights_in_t5
from .modeling_tf_t5 import TFT5EncoderModel, TFT5ForConditionalGeneration, TFT5Model, TFT5PreTrainedModel, TF_T5_PRETRAINED_MODEL_ARCHIVE_LIST

_import_structure = { "configuration_t5": ["T5_PRETRAINED_CONFIG_ARCHIVE_MAP", "T5Config"] }
if is_sentencepiece_available():
    ...
if is_tokenizers_available():
    ...
if is_torch_available():
    ...
if is_tf_available():
    ...
if is_sentencepiece_available():
    ...
if is_tokenizers_available():
    ...
if is_torch_available():
    ...
if is_tf_available():
    ...
