data_params: !!python/object:gitnetic.tasks.base_transformers.base.DataParams
  num_workers: 16
  train_data_prefix: /Users/mozharovsky/GitHub/gitnetic-ml/data/2020-07-08-dataset-byte-bpe-tokenizer-vocab10K/train.src
  val_data_prefix: /Users/mozharovsky/GitHub/gitnetic-ml/data/2020-07-08-dataset-byte-bpe-tokenizer-vocab10K/val.src
training_params: !!python/object:gitnetic.tasks.base_transformers.base.TrainingParams
  batch_size: 4
  learning_rate: 5.0e-05
  power: 1.0
  warmup_steps: 4000
  weight_decay: 0.01
