"""
This type stub file was generated by pyright.
"""

import argparse

"""Convert Reformer checkpoint."""
def set_param(torch_layer, weight, bias=...):
    ...

def set_layer_weights_in_torch_lsh(weights, torch_layer, hidden_size):
    ...

def set_layer_weights_in_torch_local(weights, torch_layer, hidden_size):
    ...

def set_block_weights_in_torch(weights, torch_block, hidden_size):
    ...

def set_model_weights_in_torch(weights, torch_model, hidden_size):
    ...

def convert_trax_checkpoint_to_pytorch(trax_model_pkl_path, config_file, pytorch_dump_path):
    ...

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    args = parser.parse_args()
