"""
This type stub file was generated by pyright.
"""

import argparse

"""Convert OpenAI GPT checkpoint."""
def convert_openai_checkpoint_to_pytorch(openai_checkpoint_folder_path, openai_config_file, pytorch_dump_folder_path):
    ...

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    args = parser.parse_args()
