"""
This type stub file was generated by pyright.
"""

import argparse

"""
This type stub file was generated by pyright.
"""
def convert_xlm_checkpoint_to_pytorch(xlm_checkpoint_path, pytorch_dump_folder_path):
    ...

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    args = parser.parse_args()
