"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from argparse import ArgumentParser

"""
This type stub file was generated by pyright.
"""
class BaseTransformersCLICommand(ABC):
    @staticmethod
    @abstractmethod
    def register_subcommand(parser: ArgumentParser):
        ...
    
    @abstractmethod
    def run(self):
        ...
    


