"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ...file_utils import _BaseLazyModule, is_tf_available, is_torch_available
from .configuration_xlm import XLMConfig, XLM_PRETRAINED_CONFIG_ARCHIVE_MAP
from .tokenization_xlm import XLMTokenizer
from .modeling_xlm import XLMForMultipleChoice, XLMForQuestionAnswering, XLMForQuestionAnsweringSimple, XLMForSequenceClassification, XLMForTokenClassification, XLMModel, XLMPreTrainedModel, XLMWithLMHeadModel, XLM_PRETRAINED_MODEL_ARCHIVE_LIST
from .modeling_tf_xlm import TFXLMForMultipleChoice, TFXLMForQuestionAnsweringSimple, TFXLMForSequenceClassification, TFXLMForTokenClassification, TFXLMMainLayer, TFXLMModel, TFXLMPreTrainedModel, TFXLMWithLMHeadModel, TF_XLM_PRETRAINED_MODEL_ARCHIVE_LIST

_import_structure = { "configuration_xlm": ["XLM_PRETRAINED_CONFIG_ARCHIVE_MAP", "XLMConfig"],"tokenization_xlm": ["XLMTokenizer"] }
if is_torch_available():
    ...
if is_tf_available():
    ...
if is_torch_available():
    ...
if is_tf_available():
    ...
