"""
This type stub file was generated by pyright.
"""

from ...utils import logging
from ..bert.tokenization_bert import BertTokenizer

"""Tokenization classes for RetriBERT."""
logger = logging.get_logger(__name__)
VOCAB_FILES_NAMES = { "vocab_file": "vocab.txt" }
PRETRAINED_VOCAB_FILES_MAP = { "vocab_file": { "yjernite/retribert-base-uncased": "https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt" } }
PRETRAINED_POSITIONAL_EMBEDDINGS_SIZES = { "yjernite/retribert-base-uncased": 512 }
PRETRAINED_INIT_CONFIGURATION = { "yjernite/retribert-base-uncased": { "do_lower_case": True } }
class RetriBertTokenizer(BertTokenizer):
    r"""
    Constructs a RetriBERT tokenizer.

    :class:`~transformers.RetroBertTokenizer` is identical to :class:`~transformers.BertTokenizer` and runs end-to-end
    tokenization: punctuation splitting and wordpiece.

    Refer to superclass :class:`~transformers.BertTokenizer` for usage examples and documentation concerning
    parameters.
    """
    vocab_files_names = ...
    pretrained_vocab_files_map = ...
    max_model_input_sizes = ...
    pretrained_init_configuration = ...
    model_input_names = ...


